import os
from github import Github
from datetime import datetime
from dotenv import load_dotenv

load_dotenv()

from github import Github, Auth

def commit_ledger(report_data: dict) -> str:
    try:
        auth = Auth.Token(os.getenv("GITHUB_TOKEN"))
        g = Github(auth=auth)
        repo = g.get_repo(os.getenv("GITHUB_REPO"))
        week = datetime.now().strftime("%Y-W%U")
        date_str = datetime.now().strftime("%B %d, %Y")
        filename = f"ledgers/week-{week}.md"

        # Build transactions table
        tx_rows = ""
        for t in report_data.get("transactions", []):
            emoji = "💰" if t["type"] == "income" else "💸"
            tx_rows += f"| {emoji} {t['type'].title()} | ₹{t['amount_inr']} | {t['category']} | {t['description']} |\n"

        content = f"""# 💜 VentureHer Weekly Ledger
## Week of {date_str}

---

## 📊 Financial Summary

| Metric | Amount |
|--------|--------|
| 💰 Total Revenue | ₹{report_data['total_revenue']} |
| 💸 Total Expenses | ₹{report_data['total_expenses']} |
| **✨ Net Profit** | **₹{report_data['net_profit']}** |
| 🔴 Biggest Cost | {report_data['top_category']} |

---

## 🎙️ AI Coach Says
> {report_data['advice']}

---

## 📋 All Transactions

| Type | Amount | Category | Description |
|------|--------|----------|-------------|
{tx_rows}

---

*🤖 Generated by VentureHer AI — {datetime.now().isoformat()}*
*Building financial independence, one week at a time. 💜*
"""
        commit_message = f"VentureHer: Week {week} — ₹{report_data['net_profit']} profit 💜"

        try:
            # Try to update if file exists
            existing = repo.get_contents(filename)
            repo.update_file(filename, commit_message, content, existing.sha)
        except:
            # Create new file
            repo.create_file(filename, commit_message, content)

        return f"https://github.com/{os.getenv('GITHUB_REPO')}/blob/main/{filename}"

    except Exception as e:
        print(f"GitHub error: {e}")
        return ""